
$(document).ready(function(){
	$('head').append('<link rel="stylesheet" href="'+getRootPath()+'/css/tm_docs.css" type="text/css" media="screen">');
	var menu1 = '<div id="panel">'
+                '<div class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner" id="advanced">'
+                     '<span class="trigger"><strong></strong><em></em></span>'
+                          '<div class="container">'
+                               '<div class="navbar-header">'
+                                    '<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">'
+										 '<span class="sr-only">Toggle navigation</span><span class="icon-bar"></span>'
+										 '<span class="icon-bar"></span><span class="icon-bar"></span>'
+                                    '</button>'
+                               '</div>'
+                               '<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">'
+                               '<ul class="nav navbar-nav">'
+                                    '<li class="home"><a href="'+getRootPath()+'/index.html" class="glyphicon glyphicon-home"></a></li>'
+                                    '<li class="divider-vertical"></li>'
+                                    '<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" title="关于我们">关于我们 <b class="caret"></b></a>'
+                                         '<ul class="dropdown-menu">'
+                                              '<li><a href="'+getRootPath()+'/aboutus/index.html" title="企业简介">企业简介</a></li>'
+                                              '<li><a href="'+getRootPath()+'/aboutus/history.html" title="发展历程">发展历程</a></li>'
+                                              '<li><a href="'+getRootPath()+'/aboutus/brand.html" title="品牌介绍">品牌介绍</a></li>'
+                                              '<li><a href="'+getRootPath()+'/aboutus/store.html" title="店铺分布">店铺分布</a></li>'
+                                              '<li><a href="'+getRootPath()+'/aboutus/team.html" title="团队介绍">团队介绍</a></li>'
+                                         '</ul>'
+                                    '</li>'
+                                    '<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" title="合作范畴">合作范畴 <b class="caret"></b></a>'
+                                         '<ul class="dropdown-menu">'
+                                              '<li><a href="'+getRootPath()+'/cooperation/index.html" title="招商加盟">招商加盟</a></li>'
+                                              '<li><a href="'+getRootPath()+'/cooperation/independent.html" title="设计师加盟">设计师加盟</a></li>'
+                                              '<li><a href="'+getRootPath()+'/cooperation/international.html" title="品牌代理">品牌代理</a></li>'
+                                         '</ul>'
+                                    '</li>'
+                                    '<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" title="产品展示">产品展示 <b class="caret"></b></a>'
+                                         '<ul class="dropdown-menu">'
+                                              '<li><a href="'+getRootPath()+'/collection/cindex.html" title="CUBFACE">CUBFACE</a></li>'
+                                         '</ul>'
+                                    '</li>'
+                                    '<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" title="新闻中心">新闻中心 <b class="caret"></b></a>'
+                                         '<ul class="dropdown-menu">'
+                                              '<li><a href="'+getRootPath()+'/pressroom/index.html" title="新闻发布">新闻发布</a></li>'
+                                              '<li><a href="'+getRootPath()+'/pressroom/photogallery.html" title="图片社">图片社</a></li>'
+                                              '<li><a href="'+getRootPath()+'/pressroom/corpimage.html" title="企业形象">企业形象</a></li>'
+                                              '<li><a href="'+getRootPath()+'/pressroom/presscontact.html" title="新闻联系">新闻联系</a></li>'
+                                         '</ul>'
+                                    '</li>'
+                                    '<li><a href="'+getRootPath()+'/aftersale/index.html" title="售后服务">售后服务</a></li>'
+                                    '<li><a href="'+getRootPath()+'/contactus/index.html" title="招聘信息">招聘信息</a></li>'
+                                    '<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" title="在线商城">在线商城 <b class="caret"></b></a>'
+                                         '<ul class="dropdown-menu">'
+                                              '<li><a href="'+getRootPath()+'/mall/index.html" title="FC垂直网站">FC垂直网站</a></li>'
+                                              '<li><a target="_blank" href="http://cubface.tmall.com" title="CUBFACE天猫旗舰店">CUBFACE天猫旗舰店</a></li>'
+                                         '</ul>'
+                                    '</li>'
+                               '</ul>'
+                           '</nav>'
+                       '</div>'
+                   '</div>'
+               '</div>';

	$('body').prepend(menu1);
 
 
	var menu2 = '<div class="container">'
+  				'<div class="row">'
+		            '<article class="col-lg-12 col-md-12 col-sm-12">'
+		                '<div class="menuBox clearfix">'
+		                   ' <nav class="navbar navbar-default navbar-static-top tm_navbar clearfix" role="navigation">'
+		                        '<ul class="nav sf-menu clearfix">'
+		                            '<li class="active"><a href="'+getRootPath()+'/index.html" title="首页">首页</a>'  
+		                            '</li>'
+		                            '<li class="sub-menu"><a href="#" title="关于我们">关于我们<span></span></a>'
+		                            	'<ul class="submenu">'
+		                                    '<li><a href="'+getRootPath()+'/aboutus/index.html" title="企业简介">企业简介</a></li>'
+		                                    '<li><a href="'+getRootPath()+'/aboutus/history.html" title="发展历程">发展历程</a></li>'
+		                                    '<li><a href="'+getRootPath()+'/aboutus/brand.html" title="品牌介绍">品牌介绍 </a></li>'
+		                                    '<li><a href="'+getRootPath()+'/aboutus/store.html" title="店铺分布">店铺分布 </a></li>'
+		                                    '<li><a href="'+getRootPath()+'/aboutus/team.html" title="团队介绍">团队介绍 </a></li>'
+		                               '</ul>'
+		                            '</li>'
+		                            '<li class="sub-menu"><a href="#" title="合作范畴">合作范畴<span></span></a>'
+		                            	'<ul class="submenu">'
+		                                    '<li><a href="'+getRootPath()+'/cooperation/index.html" title="招商加盟">招商加盟</a></li>'
+		                                    '<li><a href="'+getRootPath()+'/cooperation/independent.html" title="设计师加盟">设计师加盟</a></li>'
+		                                    '<li><a href="'+getRootPath()+'/cooperation/international.html" title="品牌代理">品牌代理 </a></li>'
+		                               '</ul>'
+		                            '</li>'
+		                            '<li class="sub-menu"><a href="#" title="产品展示">产品展示<span></span></a>'
+		                            	'<ul class="submenu">'
+		                                    '<li><a href="'+getRootPath()+'/collection/cindex.html" title="CUBFACE">CUBFACE</a></li>'
+		                               '</ul>'
+		                            '</li>'
+		                            '<li class="sub-menu"><a href="#" title="新闻中心">新闻中心<span></span></a>'
+		                            	'<ul class="submenu">'
+		                                    '<li><a href="'+getRootPath()+'/pressroom/index.html" title="新闻发布">新闻发布</a></li>'
+		                                    '<li><a href="'+getRootPath()+'/pressroom/photogallery.html" title="图片社">图片社</a></li>'
+		                                    '<li><a href="'+getRootPath()+'/pressroom/corpimage.html" title="企业形象">企业形象 </a></li>'
+		                                    '<li><a href="'+getRootPath()+'/pressroom/presscontact.html" title="新闻联系">新闻联系 </a></li>'
+		                               '</ul>'
+		                            '</li>'
+		                            '<li><a href="'+getRootPath()+'/aftersale/index.html" title="售后服务">售后服务</a></li>'
+		                            '<li><a href="'+getRootPath()+'/contactus/index.html" title="招聘信息">招聘信息</a></li>'
+		                            '<li class="sub-menu"><a href="#" title="图片社">在线商城<span></span></a>'
+		                            	'<ul class="submenu">'
+		                                    '<li><a href="'+getRootPath()+'/mall/index.html" title="在线商城">在线商城</a></li>'
+		                                    '<li><a href="http://cubface.tmall.com" title="CUBFACE天猫旗舰店">CUBFACE天猫旗舰店</a></li>'
+		                               '</ul>'
+		                            '</li>'
+		                        '</ul>'
+		                  '  </nav>'
+		               ' </div>'
+		            '</article>'
+		       ' </div>'
+		    '</div>';

	var footer1 = '<div class="container">'
+		        	'<div class="row">'
+		            '<article class="col-lg-12 col-md-12 col-sm-12">'
+		                '<ul class="bc-social-buttons">'
+				            '<li>'
+				            	'<a target="_self" title="Four Corners企业简介" href="'+getRootPath()+'aboutus/index.html">'
+									'<img alt="Four Corners企业简介" style="height: 59px;" src="'+getRootPath()+'/img/footlogo_01.png"></img>'
+								'</a>'
+				            '</li>'
+				            '<li>'
+				                '<a target="_blank" title="Four Corners中文网新浪微博" href="http://weibo.com/4corners">'
+				                    '<img alt="Four Corners中文网新浪微博" style="height: 25px;" src="'+getRootPath()+'/img/weibo_icon.jpg"></img>'
+				                '</a>'
+				            '</li>'
+				            '<li>'
+				                '<a target="_blank" title="Four Corners网易博客" href="http://four-corners.blog.163.com/">'
+				                    '<img alt="Four Corners网易博客" style="height: 25px;" src="'+getRootPath()+'/img/163net.png"></img>'
+				                '</a>'
+				            '</li>'
+				        '</ul>'
+		                '<p>&copy; Four Corners 2014 &nbsp;'
+                       '<a href="http://www.miitbeian.gov.cn"> 粤ICP备13008378号-1</a></p>'
+		                '<div>'
+						    '<a id="toTop" href="#" style="margin-right: -60px; right: 50%; display: block;">'
+						        '<span id="toTopHover" style="opacity: 0;"></span>'
+						    '</a>'
+						'</div>'
+		            '</article>'
+		        '</div>'
+		    '</div>';

	$('#sub_menu').append(menu2);

	$('#footer_homepage').append(footer1);
 
	jQuery('.sf-menu').mobileMenu();
 
});

 
